In [1]:
import pandas as pd
import numpy as np
import datetime

In [2]:
data = pd.read_csv('coin_BinanceCoin.csv')
df = pd.DataFrame(data)

#show the first five column of the data frame
#so that the use will have the idea of what the 
#data looks like

In [3]:
#check if there are any NaN
data.isnull().sum()

SNo          0
Name         0
Symbol       0
Date         0
High         0
Low          0
Open         0
Close        0
Volume       0
Marketcap    0
dtype: int64

In [4]:
#if there are NaN or 0 on features like high, low, open, close,
#one of the solutions is to eliminate the corresponding row.
#Another way is to replace them with some value like median.
#However, in my opinion,if missing value does occur in stock
#market, we can't simply use median to replace it because the price
#varies day to day enormously. Moreover, even if we do use median
#or other values like average value of a certain period, we can't
#make sure that the price in this period are similar
#So, removing it might be the best way to keep out data as real
#as possible

df.dropna(subset=['High', 'Low', 'Open','Close'])

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
0,1,Binance Coin,BNB,2017-07-26 23:59:59,0.109013,0.099266,0.105893,0.105138,2.003950e+05,1.051380e+07
1,2,Binance Coin,BNB,2017-07-27 23:59:59,0.108479,0.100888,0.105108,0.107737,3.444990e+05,1.077370e+07
2,3,Binance Coin,BNB,2017-07-28 23:59:59,0.109019,0.101473,0.107632,0.104067,3.425680e+05,1.040670e+07
3,4,Binance Coin,BNB,2017-07-29 23:59:59,0.111264,0.101108,0.104782,0.107811,3.402180e+05,1.078110e+07
4,5,Binance Coin,BNB,2017-07-30 23:59:59,0.108138,0.103162,0.107935,0.106414,2.242610e+05,1.064140e+07
...,...,...,...,...,...,...,...,...,...,...
1308,1309,Binance Coin,BNB,2021-02-23 23:59:59,268.536845,190.412463,267.364425,230.994252,8.280753e+09,3.569619e+10
1309,1310,Binance Coin,BNB,2021-02-24 23:59:59,280.088196,214.524714,231.121604,254.359132,7.154122e+09,3.930683e+10
1310,1311,Binance Coin,BNB,2021-02-25 23:59:59,264.705134,233.885956,254.467606,233.885956,4.059853e+09,3.614305e+10
1311,1312,Binance Coin,BNB,2021-02-26 23:59:59,238.755012,210.310761,235.270287,221.680429,4.167146e+09,3.425689e+10
1312,1313,Binance Coin,BNB,2021-02-27 23:59:59,237.179435,220.099401,221.980905,225.249443,2.755271e+09,3.480842e+10

In [5]:
#The data from Kaggle on Date column has the time it got fetched
#In order to keep the the cleaness of the data, just remove some
#excess infomation
df['Date'] = df['Date'].str.replace(r'23:59:59','')
df['Date'] = pd.to_datetime(df.Date)

In [6]:
#The 'Name' column of the dataset from Kaggle only
#has one name which means the whole table is about single
#crypto currency. 
#If there are more than two, we need to categorize
#them by the their name then their date

num_unique_coin = df['Name'].nunique()
unique_coin_list = df['Name'].unique()
if num_unique_coin == 1:
    del df['Name']
    del df['Symbol']
elif num_unique_coin > 1:
    df['Name'] = sorted(df['Name'])
    df['Date'] = sorted(df['Date'])
    df['Symbol'] = sorted(df['Date'])

In [7]:
#single crypto section:
#There are some volumes that might be 0 because
#the trading of this currency has not yet started,
#so from my point of view the solution is to make 
#two different df which are before and after start trading

#multiple cryptos section:
#it might be better to separate different cryptos into
#different data frame which will be easier to analyze and
#then separate the same crypto based on the number of volume

#By check the unique_coin_list, you will know what are the
#unique coins in this table

if num_unique_coin == 1:
    df_before_trading = df.loc[df.Volume == 0]
    df_after_trading = df.loc[df.Volume > 0]
elif num_unique_coin > 1:
    df_before_trading = df.loc[(df.Name == 'Name_of_crypto') & (df.Volume == 0)]
    df_after_trading = df.loc[(df.Name == 'Name_of_crypto') & (df.Volume == 0)]
    #Separate the original data frame based on the number of cryptos in the table

In [8]:
if len(df_before_trading) > 0:
    df_before_trading.to_csv(r'C:\Users\shuny\OneDrive\Desktop\Crypto analysis\Binance\Binance_before_trading_clean.csv', index=False)
if len(df_after_trading) > 0:    
    df_after_trading.to_csv(r'C:\Users\shuny\OneDrive\Desktop\Crypto analysis\Binance\Binance_after_trading_clean.csv', index=False)
# #if you have more data frame, just add it here with the same format above to export to CSVs.